### ISSUE TITLE
Error:Failed to resolve: :crtaci-arm64:  and :crtaci-arm7:

### ISSUE THREAD

**Issue by qadir-genetech** [gen2brain/crtaci#1]
I am trying to build this project in android studio.

I am getting error on gradle build i.e 

Error:Failed to resolve: :crtaci-arm64:
Error:Failed to resolve: :crtaci-arm7:

see screen shot here
http://prntscr.com/db54od

looks like I am missing some lib named "Crtaci" 
I am getting this in all my activities as well, see screen shot here
http://prntscr.com/db552f

Where I can find this lib?

Waiting for your reply

**Comment by gen2brain** [comment]
Library is in backend/crtaci (source). You need Go and gomobile so you can build shared library and java bindings. There is a make.bash file there you can use, but something like this is enough:
```gomobile bind -v -x -o build/crtaci.aar -target android/arm,android/arm64,android/386 -ldflags "-s -w" github.com/gen2brain/crtaci/backend/crtaci```

You can also extract library from .apk, just unzip it and copy .aar file. For next release I can probably also add .aar binary file to android dir.

**Comment by gen2brain** [comment]
Ok, not sure if .aar can be found in apk, but I added binaries to libs/ dir in 90c4423e9bc5fc6c05f7c5a1741559f01831de64 .

**Comment by qadir-genetech** [comment]
Wow! thank for quick help.
This resolved my issue. 

Can I see the code in aar files?

**Comment by gen2brain** [comment]
Sure, it is in https://github.com/gen2brain/crtaci/blob/master/backend/crtaci/crtaci.go , and in filters.go are censored words and ids.

**Comment by gen2brain** [comment]
gomobile will compile it as c-shared library and will generate Java bindings you then use in your app. All exported/uppercased functions and vars will be available.

**Comment by qadir-genetech** [comment]
Thanks alot for your support. This really help 👍

**Comment by qadir-genetech** [comment]
@gen2brain .go file is written in what?

**Comment by gen2brain** [comment]
It is written in https://golang.org . If you think in what IDE I use vim editor.

**Comment by qadir-genetech** [comment]
OK, go is an programming language.

can you explain what basically https://github.com/gen2brain/crtaci/blob/master/backend/crtaci/crtaci.go is doing ?

**Comment by gen2brain** [comment]
Search() searches youtube, vimeo and dailymotion and returns json string. List() returns list of predefined cartoon characters. Extract() returns real video url you can use in player.

**Comment by qadir-genetech** [comment]
Wow! this is awesome. 
means I can use this aar lib in my android project to search any videos (not just of cartoons) from youtube,vemio,dailymotion . right?

**Comment by gen2brain** [comment]
Yes, but you will need to modify it a little. Currently functions expect a *Character, but that can be just plain query string, so you can remove a lot of code. You will alo need to get api keys from youtube and vimeo, for dailymotion there is no need, their public api is enough.

**Comment by qadir-genetech** [comment]
OK fine. one more thing to ask. is this same .go library has been used for your php(web)/windows/mac version?

**Comment by gen2brain** [comment]
For php you can build HTTP server https://github.com/gen2brain/crtaci/tree/master/backend/crtaci/server . Windows, Linux and Mac versions used Python before (you can check, it is also in source), and were sending requests to HTTP server, response you get is json.
Now there is also a Go desktop version, that just calls native functions.

**Comment by qadir-genetech** [comment]
I am try to play the youtube url video in your PlayerActivity.java in webview
https://www.youtube.com/embed/bA-qURwcwkA?fs=1&autoplay=1&disablekb=1&showinfo=0

its not opening.
![device-2016-11-24-183230](https://cloud.githubusercontent.com/assets/14326497/20600143/e4c931e4-b273-11e6-94d6-9be058aa0810.png)

**Comment by gen2brain** [comment]
WebView is used only as a fallback, Crtaci.extract(service, videoId) gets real url, it will retry 3 times if player fails with that url and will fallback to webview. But that looks like some connectivity error.

**Comment by qadir-genetech** [comment]
I just have check the connectivity and tested above url is opening in chrome and youtube (app) in my android device and video plays flawlessly 
but it fails playing in your webview. 

basically what I am trying to do is only wants to open the video (from defferent sources i.e youtube, dailymotion or vimeo) in webview not in the player.

here is the code

```
 public void playYouTube(String id) {
        String params = "?fs=1&autoplay=1&disablekb=1&showinfo=0";
        String url = "https://www.youtube.com/embed/" + id + params;

        Log.e("playYouTube", url+""); // this prints the url https://www.youtube.com/embed/bA-qURwcwkA?fs=1&autoplay=1&disablekb=1&showinfo=0

        webViewPlayer(url);
    }
```

```
public void webViewPlayer(String url) {
        setContentView(R.layout.player_webview);
        webView = (VideoEnabledWebView) findViewById(R.id.webView);

        View nonVideoLayout = findViewById(R.id.nonVideoLayout);
        ViewGroup videoLayout = (ViewGroup) findViewById(R.id.videoLayout);
        View loadingView = getLayoutInflater().inflate(R.layout.loading, null);

        webChromeClient = new VideoEnabledWebChromeClient(nonVideoLayout, videoLayout, loadingView);
        webView.setWebChromeClient(webChromeClient);

        webView.setKeepScreenOn(true);
        webView.setBackgroundColor(0x00000000);
        webView.loadUrl(url);
    }
```

did I am missing something?

**Comment by gen2brain** [comment]
Not sure, check VideoEnabledWebView and VideoEnabledWebChromeClient, that is not my code. If you are not going to use real player then maybe better use YouTubeStandalonePlayer, YouTubePlayerView etc. I guess Vimeo and DailyMotion probably have equivalent.

**Comment by qadir-genetech** [comment]
:(
